# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fenix/projects/tsfile

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fenix/projects/tsfile

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fenix/projects/tsfile/CMakeFiles /home/fenix/projects/tsfile/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fenix/projects/tsfile/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cppcheck

# Build rule for target.
cppcheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cppcheck
.PHONY : cppcheck

# fast build rule for target.
cppcheck/fast:
	$(MAKE) -f CMakeFiles/cppcheck.dir/build.make CMakeFiles/cppcheck.dir/build
.PHONY : cppcheck/fast

#=============================================================================
# Target rules for targets named clang-format

# Build rule for target.
clang-format: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clang-format
.PHONY : clang-format

# fast build rule for target.
clang-format/fast:
	$(MAKE) -f CMakeFiles/clang-format.dir/build.make CMakeFiles/clang-format.dir/build
.PHONY : clang-format/fast

#=============================================================================
# Target rules for targets named clang-tidy

# Build rule for target.
clang-tidy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clang-tidy
.PHONY : clang-tidy

# fast build rule for target.
clang-tidy/fast:
	$(MAKE) -f CMakeFiles/clang-tidy.dir/build.make CMakeFiles/clang-tidy.dir/build
.PHONY : clang-tidy/fast

#=============================================================================
# Target rules for targets named coverage-report

# Build rule for target.
coverage-report: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coverage-report
.PHONY : coverage-report

# fast build rule for target.
coverage-report/fast:
	$(MAKE) -f CMakeFiles/coverage-report.dir/build.make CMakeFiles/coverage-report.dir/build
.PHONY : coverage-report/fast

#=============================================================================
# Target rules for targets named unit_test

# Build rule for target.
unit_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_test
.PHONY : unit_test

# fast build rule for target.
unit_test/fast:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/build
.PHONY : unit_test/fast

#=============================================================================
# Target rules for targets named coverage

# Build rule for target.
coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coverage
.PHONY : coverage

# fast build rule for target.
coverage/fast:
	$(MAKE) -f CMakeFiles/coverage.dir/build.make CMakeFiles/coverage.dir/build
.PHONY : coverage/fast

#=============================================================================
# Target rules for targets named tsfile

# Build rule for target.
tsfile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tsfile
.PHONY : tsfile

# fast build rule for target.
tsfile/fast:
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/build
.PHONY : tsfile/fast

src/tsfile/common/bitmap.o: src/tsfile/common/bitmap.cc.o

.PHONY : src/tsfile/common/bitmap.o

# target to build an object file
src/tsfile/common/bitmap.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/bitmap.cc.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/bitmap.cc.o
.PHONY : src/tsfile/common/bitmap.cc.o

src/tsfile/common/bitmap.i: src/tsfile/common/bitmap.cc.i

.PHONY : src/tsfile/common/bitmap.i

# target to preprocess a source file
src/tsfile/common/bitmap.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/bitmap.cc.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/bitmap.cc.i
.PHONY : src/tsfile/common/bitmap.cc.i

src/tsfile/common/bitmap.s: src/tsfile/common/bitmap.cc.s

.PHONY : src/tsfile/common/bitmap.s

# target to generate assembly for a file
src/tsfile/common/bitmap.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/bitmap.cc.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/bitmap.cc.s
.PHONY : src/tsfile/common/bitmap.cc.s

src/tsfile/common/hasher.o: src/tsfile/common/hasher.cc.o

.PHONY : src/tsfile/common/hasher.o

# target to build an object file
src/tsfile/common/hasher.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/hasher.cc.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/hasher.cc.o
.PHONY : src/tsfile/common/hasher.cc.o

src/tsfile/common/hasher.i: src/tsfile/common/hasher.cc.i

.PHONY : src/tsfile/common/hasher.i

# target to preprocess a source file
src/tsfile/common/hasher.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/hasher.cc.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/hasher.cc.i
.PHONY : src/tsfile/common/hasher.cc.i

src/tsfile/common/hasher.s: src/tsfile/common/hasher.cc.s

.PHONY : src/tsfile/common/hasher.s

# target to generate assembly for a file
src/tsfile/common/hasher.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/hasher.cc.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/hasher.cc.s
.PHONY : src/tsfile/common/hasher.cc.s

src/tsfile/common/murmurhash3.o: src/tsfile/common/murmurhash3.cc.o

.PHONY : src/tsfile/common/murmurhash3.o

# target to build an object file
src/tsfile/common/murmurhash3.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/murmurhash3.cc.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/murmurhash3.cc.o
.PHONY : src/tsfile/common/murmurhash3.cc.o

src/tsfile/common/murmurhash3.i: src/tsfile/common/murmurhash3.cc.i

.PHONY : src/tsfile/common/murmurhash3.i

# target to preprocess a source file
src/tsfile/common/murmurhash3.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/murmurhash3.cc.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/murmurhash3.cc.i
.PHONY : src/tsfile/common/murmurhash3.cc.i

src/tsfile/common/murmurhash3.s: src/tsfile/common/murmurhash3.cc.s

.PHONY : src/tsfile/common/murmurhash3.s

# target to generate assembly for a file
src/tsfile/common/murmurhash3.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/murmurhash3.cc.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/murmurhash3.cc.s
.PHONY : src/tsfile/common/murmurhash3.cc.s

src/tsfile/common/siphash.o: src/tsfile/common/siphash.cc.o

.PHONY : src/tsfile/common/siphash.o

# target to build an object file
src/tsfile/common/siphash.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/siphash.cc.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/siphash.cc.o
.PHONY : src/tsfile/common/siphash.cc.o

src/tsfile/common/siphash.i: src/tsfile/common/siphash.cc.i

.PHONY : src/tsfile/common/siphash.i

# target to preprocess a source file
src/tsfile/common/siphash.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/siphash.cc.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/siphash.cc.i
.PHONY : src/tsfile/common/siphash.cc.i

src/tsfile/common/siphash.s: src/tsfile/common/siphash.cc.s

.PHONY : src/tsfile/common/siphash.s

# target to generate assembly for a file
src/tsfile/common/siphash.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/common/siphash.cc.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/common/siphash.cc.s
.PHONY : src/tsfile/common/siphash.cc.s

src/tsfile/io/path.o: src/tsfile/io/path.cc.o

.PHONY : src/tsfile/io/path.o

# target to build an object file
src/tsfile/io/path.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/io/path.cc.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/io/path.cc.o
.PHONY : src/tsfile/io/path.cc.o

src/tsfile/io/path.i: src/tsfile/io/path.cc.i

.PHONY : src/tsfile/io/path.i

# target to preprocess a source file
src/tsfile/io/path.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/io/path.cc.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/io/path.cc.i
.PHONY : src/tsfile/io/path.cc.i

src/tsfile/io/path.s: src/tsfile/io/path.cc.s

.PHONY : src/tsfile/io/path.s

# target to generate assembly for a file
src/tsfile/io/path.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/io/path.cc.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/io/path.cc.s
.PHONY : src/tsfile/io/path.cc.s

src/tsfile/io/sequence_reader.o: src/tsfile/io/sequence_reader.cc.o

.PHONY : src/tsfile/io/sequence_reader.o

# target to build an object file
src/tsfile/io/sequence_reader.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/io/sequence_reader.cc.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/io/sequence_reader.cc.o
.PHONY : src/tsfile/io/sequence_reader.cc.o

src/tsfile/io/sequence_reader.i: src/tsfile/io/sequence_reader.cc.i

.PHONY : src/tsfile/io/sequence_reader.i

# target to preprocess a source file
src/tsfile/io/sequence_reader.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/io/sequence_reader.cc.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/io/sequence_reader.cc.i
.PHONY : src/tsfile/io/sequence_reader.cc.i

src/tsfile/io/sequence_reader.s: src/tsfile/io/sequence_reader.cc.s

.PHONY : src/tsfile/io/sequence_reader.s

# target to generate assembly for a file
src/tsfile/io/sequence_reader.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/io/sequence_reader.cc.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/io/sequence_reader.cc.s
.PHONY : src/tsfile/io/sequence_reader.cc.s

src/tsfile/model/chunk.o: src/tsfile/model/chunk.cc.o

.PHONY : src/tsfile/model/chunk.o

# target to build an object file
src/tsfile/model/chunk.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk.cc.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk.cc.o
.PHONY : src/tsfile/model/chunk.cc.o

src/tsfile/model/chunk.i: src/tsfile/model/chunk.cc.i

.PHONY : src/tsfile/model/chunk.i

# target to preprocess a source file
src/tsfile/model/chunk.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk.cc.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk.cc.i
.PHONY : src/tsfile/model/chunk.cc.i

src/tsfile/model/chunk.s: src/tsfile/model/chunk.cc.s

.PHONY : src/tsfile/model/chunk.s

# target to generate assembly for a file
src/tsfile/model/chunk.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk.cc.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk.cc.s
.PHONY : src/tsfile/model/chunk.cc.s

src/tsfile/model/chunk_group.o: src/tsfile/model/chunk_group.cc.o

.PHONY : src/tsfile/model/chunk_group.o

# target to build an object file
src/tsfile/model/chunk_group.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk_group.cc.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk_group.cc.o
.PHONY : src/tsfile/model/chunk_group.cc.o

src/tsfile/model/chunk_group.i: src/tsfile/model/chunk_group.cc.i

.PHONY : src/tsfile/model/chunk_group.i

# target to preprocess a source file
src/tsfile/model/chunk_group.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk_group.cc.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk_group.cc.i
.PHONY : src/tsfile/model/chunk_group.cc.i

src/tsfile/model/chunk_group.s: src/tsfile/model/chunk_group.cc.s

.PHONY : src/tsfile/model/chunk_group.s

# target to generate assembly for a file
src/tsfile/model/chunk_group.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk_group.cc.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk_group.cc.s
.PHONY : src/tsfile/model/chunk_group.cc.s

src/tsfile/model/chunk_group_footer.o: src/tsfile/model/chunk_group_footer.cc.o

.PHONY : src/tsfile/model/chunk_group_footer.o

# target to build an object file
src/tsfile/model/chunk_group_footer.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk_group_footer.cc.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk_group_footer.cc.o
.PHONY : src/tsfile/model/chunk_group_footer.cc.o

src/tsfile/model/chunk_group_footer.i: src/tsfile/model/chunk_group_footer.cc.i

.PHONY : src/tsfile/model/chunk_group_footer.i

# target to preprocess a source file
src/tsfile/model/chunk_group_footer.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk_group_footer.cc.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk_group_footer.cc.i
.PHONY : src/tsfile/model/chunk_group_footer.cc.i

src/tsfile/model/chunk_group_footer.s: src/tsfile/model/chunk_group_footer.cc.s

.PHONY : src/tsfile/model/chunk_group_footer.s

# target to generate assembly for a file
src/tsfile/model/chunk_group_footer.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk_group_footer.cc.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk_group_footer.cc.s
.PHONY : src/tsfile/model/chunk_group_footer.cc.s

src/tsfile/model/chunk_header.o: src/tsfile/model/chunk_header.cc.o

.PHONY : src/tsfile/model/chunk_header.o

# target to build an object file
src/tsfile/model/chunk_header.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk_header.cc.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk_header.cc.o
.PHONY : src/tsfile/model/chunk_header.cc.o

src/tsfile/model/chunk_header.i: src/tsfile/model/chunk_header.cc.i

.PHONY : src/tsfile/model/chunk_header.i

# target to preprocess a source file
src/tsfile/model/chunk_header.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk_header.cc.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk_header.cc.i
.PHONY : src/tsfile/model/chunk_header.cc.i

src/tsfile/model/chunk_header.s: src/tsfile/model/chunk_header.cc.s

.PHONY : src/tsfile/model/chunk_header.s

# target to generate assembly for a file
src/tsfile/model/chunk_header.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/chunk_header.cc.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/chunk_header.cc.s
.PHONY : src/tsfile/model/chunk_header.cc.s

src/tsfile/model/page_header.o: src/tsfile/model/page_header.cc.o

.PHONY : src/tsfile/model/page_header.o

# target to build an object file
src/tsfile/model/page_header.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/page_header.cc.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/page_header.cc.o
.PHONY : src/tsfile/model/page_header.cc.o

src/tsfile/model/page_header.i: src/tsfile/model/page_header.cc.i

.PHONY : src/tsfile/model/page_header.i

# target to preprocess a source file
src/tsfile/model/page_header.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/page_header.cc.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/page_header.cc.i
.PHONY : src/tsfile/model/page_header.cc.i

src/tsfile/model/page_header.s: src/tsfile/model/page_header.cc.s

.PHONY : src/tsfile/model/page_header.s

# target to generate assembly for a file
src/tsfile/model/page_header.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/model/page_header.cc.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/model/page_header.cc.s
.PHONY : src/tsfile/model/page_header.cc.s

test/common/test_bitmap.o: test/common/test_bitmap.cc.o

.PHONY : test/common/test_bitmap.o

# target to build an object file
test/common/test_bitmap.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/common/test_bitmap.cc.o
.PHONY : test/common/test_bitmap.cc.o

test/common/test_bitmap.i: test/common/test_bitmap.cc.i

.PHONY : test/common/test_bitmap.i

# target to preprocess a source file
test/common/test_bitmap.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/common/test_bitmap.cc.i
.PHONY : test/common/test_bitmap.cc.i

test/common/test_bitmap.s: test/common/test_bitmap.cc.s

.PHONY : test/common/test_bitmap.s

# target to generate assembly for a file
test/common/test_bitmap.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/common/test_bitmap.cc.s
.PHONY : test/common/test_bitmap.cc.s

test/common/test_bytebuffer.o: test/common/test_bytebuffer.cc.o

.PHONY : test/common/test_bytebuffer.o

# target to build an object file
test/common/test_bytebuffer.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/common/test_bytebuffer.cc.o
.PHONY : test/common/test_bytebuffer.cc.o

test/common/test_bytebuffer.i: test/common/test_bytebuffer.cc.i

.PHONY : test/common/test_bytebuffer.i

# target to preprocess a source file
test/common/test_bytebuffer.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/common/test_bytebuffer.cc.i
.PHONY : test/common/test_bytebuffer.cc.i

test/common/test_bytebuffer.s: test/common/test_bytebuffer.cc.s

.PHONY : test/common/test_bytebuffer.s

# target to generate assembly for a file
test/common/test_bytebuffer.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/common/test_bytebuffer.cc.s
.PHONY : test/common/test_bytebuffer.cc.s

test/common/test_hash.o: test/common/test_hash.cc.o

.PHONY : test/common/test_hash.o

# target to build an object file
test/common/test_hash.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/common/test_hash.cc.o
.PHONY : test/common/test_hash.cc.o

test/common/test_hash.i: test/common/test_hash.cc.i

.PHONY : test/common/test_hash.i

# target to preprocess a source file
test/common/test_hash.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/common/test_hash.cc.i
.PHONY : test/common/test_hash.cc.i

test/common/test_hash.s: test/common/test_hash.cc.s

.PHONY : test/common/test_hash.s

# target to generate assembly for a file
test/common/test_hash.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/common/test_hash.cc.s
.PHONY : test/common/test_hash.cc.s

test/model/test_bloomfilter.o: test/model/test_bloomfilter.cc.o

.PHONY : test/model/test_bloomfilter.o

# target to build an object file
test/model/test_bloomfilter.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_bloomfilter.cc.o
.PHONY : test/model/test_bloomfilter.cc.o

test/model/test_bloomfilter.i: test/model/test_bloomfilter.cc.i

.PHONY : test/model/test_bloomfilter.i

# target to preprocess a source file
test/model/test_bloomfilter.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_bloomfilter.cc.i
.PHONY : test/model/test_bloomfilter.cc.i

test/model/test_bloomfilter.s: test/model/test_bloomfilter.cc.s

.PHONY : test/model/test_bloomfilter.s

# target to generate assembly for a file
test/model/test_bloomfilter.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_bloomfilter.cc.s
.PHONY : test/model/test_bloomfilter.cc.s

test/model/test_chunk.o: test/model/test_chunk.cc.o

.PHONY : test/model/test_chunk.o

# target to build an object file
test/model/test_chunk.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_chunk.cc.o
.PHONY : test/model/test_chunk.cc.o

test/model/test_chunk.i: test/model/test_chunk.cc.i

.PHONY : test/model/test_chunk.i

# target to preprocess a source file
test/model/test_chunk.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_chunk.cc.i
.PHONY : test/model/test_chunk.cc.i

test/model/test_chunk.s: test/model/test_chunk.cc.s

.PHONY : test/model/test_chunk.s

# target to generate assembly for a file
test/model/test_chunk.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_chunk.cc.s
.PHONY : test/model/test_chunk.cc.s

test/model/test_chunkgroup.o: test/model/test_chunkgroup.cc.o

.PHONY : test/model/test_chunkgroup.o

# target to build an object file
test/model/test_chunkgroup.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_chunkgroup.cc.o
.PHONY : test/model/test_chunkgroup.cc.o

test/model/test_chunkgroup.i: test/model/test_chunkgroup.cc.i

.PHONY : test/model/test_chunkgroup.i

# target to preprocess a source file
test/model/test_chunkgroup.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_chunkgroup.cc.i
.PHONY : test/model/test_chunkgroup.cc.i

test/model/test_chunkgroup.s: test/model/test_chunkgroup.cc.s

.PHONY : test/model/test_chunkgroup.s

# target to generate assembly for a file
test/model/test_chunkgroup.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_chunkgroup.cc.s
.PHONY : test/model/test_chunkgroup.cc.s

test/test_main.o: test/test_main.cc.o

.PHONY : test/test_main.o

# target to build an object file
test/test_main.cc.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/test_main.cc.o
.PHONY : test/test_main.cc.o

test/test_main.i: test/test_main.cc.i

.PHONY : test/test_main.i

# target to preprocess a source file
test/test_main.cc.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/test_main.cc.i
.PHONY : test/test_main.cc.i

test/test_main.s: test/test_main.cc.s

.PHONY : test/test_main.s

# target to generate assembly for a file
test/test_main.cc.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/test_main.cc.s
.PHONY : test/test_main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... cppcheck"
	@echo "... clang-format"
	@echo "... clang-tidy"
	@echo "... coverage-report"
	@echo "... unit_test"
	@echo "... coverage"
	@echo "... tsfile"
	@echo "... src/tsfile/common/bitmap.o"
	@echo "... src/tsfile/common/bitmap.i"
	@echo "... src/tsfile/common/bitmap.s"
	@echo "... src/tsfile/common/hasher.o"
	@echo "... src/tsfile/common/hasher.i"
	@echo "... src/tsfile/common/hasher.s"
	@echo "... src/tsfile/common/murmurhash3.o"
	@echo "... src/tsfile/common/murmurhash3.i"
	@echo "... src/tsfile/common/murmurhash3.s"
	@echo "... src/tsfile/common/siphash.o"
	@echo "... src/tsfile/common/siphash.i"
	@echo "... src/tsfile/common/siphash.s"
	@echo "... src/tsfile/io/path.o"
	@echo "... src/tsfile/io/path.i"
	@echo "... src/tsfile/io/path.s"
	@echo "... src/tsfile/io/sequence_reader.o"
	@echo "... src/tsfile/io/sequence_reader.i"
	@echo "... src/tsfile/io/sequence_reader.s"
	@echo "... src/tsfile/model/chunk.o"
	@echo "... src/tsfile/model/chunk.i"
	@echo "... src/tsfile/model/chunk.s"
	@echo "... src/tsfile/model/chunk_group.o"
	@echo "... src/tsfile/model/chunk_group.i"
	@echo "... src/tsfile/model/chunk_group.s"
	@echo "... src/tsfile/model/chunk_group_footer.o"
	@echo "... src/tsfile/model/chunk_group_footer.i"
	@echo "... src/tsfile/model/chunk_group_footer.s"
	@echo "... src/tsfile/model/chunk_header.o"
	@echo "... src/tsfile/model/chunk_header.i"
	@echo "... src/tsfile/model/chunk_header.s"
	@echo "... src/tsfile/model/page_header.o"
	@echo "... src/tsfile/model/page_header.i"
	@echo "... src/tsfile/model/page_header.s"
	@echo "... test/common/test_bitmap.o"
	@echo "... test/common/test_bitmap.i"
	@echo "... test/common/test_bitmap.s"
	@echo "... test/common/test_bytebuffer.o"
	@echo "... test/common/test_bytebuffer.i"
	@echo "... test/common/test_bytebuffer.s"
	@echo "... test/common/test_hash.o"
	@echo "... test/common/test_hash.i"
	@echo "... test/common/test_hash.s"
	@echo "... test/model/test_bloomfilter.o"
	@echo "... test/model/test_bloomfilter.i"
	@echo "... test/model/test_bloomfilter.s"
	@echo "... test/model/test_chunk.o"
	@echo "... test/model/test_chunk.i"
	@echo "... test/model/test_chunk.s"
	@echo "... test/model/test_chunkgroup.o"
	@echo "... test/model/test_chunkgroup.i"
	@echo "... test/model/test_chunkgroup.s"
	@echo "... test/test_main.o"
	@echo "... test/test_main.i"
	@echo "... test/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

