# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fenix/projects/tsfile

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fenix/projects/tsfile

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fenix/projects/tsfile/CMakeFiles /home/fenix/projects/tsfile/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fenix/projects/tsfile/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clang-format

# Build rule for target.
clang-format: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clang-format
.PHONY : clang-format

# fast build rule for target.
clang-format/fast:
	$(MAKE) -f CMakeFiles/clang-format.dir/build.make CMakeFiles/clang-format.dir/build
.PHONY : clang-format/fast

#=============================================================================
# Target rules for targets named unit_test

# Build rule for target.
unit_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_test
.PHONY : unit_test

# fast build rule for target.
unit_test/fast:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/build
.PHONY : unit_test/fast

#=============================================================================
# Target rules for targets named tsfile

# Build rule for target.
tsfile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tsfile
.PHONY : tsfile

# fast build rule for target.
tsfile/fast:
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/build
.PHONY : tsfile/fast

src/tsfile/chunk.o: src/tsfile/chunk.cpp.o

.PHONY : src/tsfile/chunk.o

# target to build an object file
src/tsfile/chunk.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk.cpp.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk.cpp.o
.PHONY : src/tsfile/chunk.cpp.o

src/tsfile/chunk.i: src/tsfile/chunk.cpp.i

.PHONY : src/tsfile/chunk.i

# target to preprocess a source file
src/tsfile/chunk.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk.cpp.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk.cpp.i
.PHONY : src/tsfile/chunk.cpp.i

src/tsfile/chunk.s: src/tsfile/chunk.cpp.s

.PHONY : src/tsfile/chunk.s

# target to generate assembly for a file
src/tsfile/chunk.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk.cpp.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk.cpp.s
.PHONY : src/tsfile/chunk.cpp.s

src/tsfile/chunk_group.o: src/tsfile/chunk_group.cpp.o

.PHONY : src/tsfile/chunk_group.o

# target to build an object file
src/tsfile/chunk_group.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk_group.cpp.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk_group.cpp.o
.PHONY : src/tsfile/chunk_group.cpp.o

src/tsfile/chunk_group.i: src/tsfile/chunk_group.cpp.i

.PHONY : src/tsfile/chunk_group.i

# target to preprocess a source file
src/tsfile/chunk_group.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk_group.cpp.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk_group.cpp.i
.PHONY : src/tsfile/chunk_group.cpp.i

src/tsfile/chunk_group.s: src/tsfile/chunk_group.cpp.s

.PHONY : src/tsfile/chunk_group.s

# target to generate assembly for a file
src/tsfile/chunk_group.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk_group.cpp.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk_group.cpp.s
.PHONY : src/tsfile/chunk_group.cpp.s

src/tsfile/chunk_group_footer.o: src/tsfile/chunk_group_footer.cpp.o

.PHONY : src/tsfile/chunk_group_footer.o

# target to build an object file
src/tsfile/chunk_group_footer.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk_group_footer.cpp.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk_group_footer.cpp.o
.PHONY : src/tsfile/chunk_group_footer.cpp.o

src/tsfile/chunk_group_footer.i: src/tsfile/chunk_group_footer.cpp.i

.PHONY : src/tsfile/chunk_group_footer.i

# target to preprocess a source file
src/tsfile/chunk_group_footer.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk_group_footer.cpp.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk_group_footer.cpp.i
.PHONY : src/tsfile/chunk_group_footer.cpp.i

src/tsfile/chunk_group_footer.s: src/tsfile/chunk_group_footer.cpp.s

.PHONY : src/tsfile/chunk_group_footer.s

# target to generate assembly for a file
src/tsfile/chunk_group_footer.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk_group_footer.cpp.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk_group_footer.cpp.s
.PHONY : src/tsfile/chunk_group_footer.cpp.s

src/tsfile/chunk_header.o: src/tsfile/chunk_header.cpp.o

.PHONY : src/tsfile/chunk_header.o

# target to build an object file
src/tsfile/chunk_header.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk_header.cpp.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk_header.cpp.o
.PHONY : src/tsfile/chunk_header.cpp.o

src/tsfile/chunk_header.i: src/tsfile/chunk_header.cpp.i

.PHONY : src/tsfile/chunk_header.i

# target to preprocess a source file
src/tsfile/chunk_header.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk_header.cpp.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk_header.cpp.i
.PHONY : src/tsfile/chunk_header.cpp.i

src/tsfile/chunk_header.s: src/tsfile/chunk_header.cpp.s

.PHONY : src/tsfile/chunk_header.s

# target to generate assembly for a file
src/tsfile/chunk_header.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/chunk_header.cpp.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/chunk_header.cpp.s
.PHONY : src/tsfile/chunk_header.cpp.s

src/tsfile/hasher.o: src/tsfile/hasher.cpp.o

.PHONY : src/tsfile/hasher.o

# target to build an object file
src/tsfile/hasher.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/hasher.cpp.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/hasher.cpp.o
.PHONY : src/tsfile/hasher.cpp.o

src/tsfile/hasher.i: src/tsfile/hasher.cpp.i

.PHONY : src/tsfile/hasher.i

# target to preprocess a source file
src/tsfile/hasher.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/hasher.cpp.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/hasher.cpp.i
.PHONY : src/tsfile/hasher.cpp.i

src/tsfile/hasher.s: src/tsfile/hasher.cpp.s

.PHONY : src/tsfile/hasher.s

# target to generate assembly for a file
src/tsfile/hasher.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/hasher.cpp.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/hasher.cpp.s
.PHONY : src/tsfile/hasher.cpp.s

src/tsfile/path.o: src/tsfile/path.cpp.o

.PHONY : src/tsfile/path.o

# target to build an object file
src/tsfile/path.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/path.cpp.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/path.cpp.o
.PHONY : src/tsfile/path.cpp.o

src/tsfile/path.i: src/tsfile/path.cpp.i

.PHONY : src/tsfile/path.i

# target to preprocess a source file
src/tsfile/path.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/path.cpp.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/path.cpp.i
.PHONY : src/tsfile/path.cpp.i

src/tsfile/path.s: src/tsfile/path.cpp.s

.PHONY : src/tsfile/path.s

# target to generate assembly for a file
src/tsfile/path.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/path.cpp.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/path.cpp.s
.PHONY : src/tsfile/path.cpp.s

src/tsfile/sequence_reader.o: src/tsfile/sequence_reader.cpp.o

.PHONY : src/tsfile/sequence_reader.o

# target to build an object file
src/tsfile/sequence_reader.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/sequence_reader.cpp.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/sequence_reader.cpp.o
.PHONY : src/tsfile/sequence_reader.cpp.o

src/tsfile/sequence_reader.i: src/tsfile/sequence_reader.cpp.i

.PHONY : src/tsfile/sequence_reader.i

# target to preprocess a source file
src/tsfile/sequence_reader.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/sequence_reader.cpp.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/sequence_reader.cpp.i
.PHONY : src/tsfile/sequence_reader.cpp.i

src/tsfile/sequence_reader.s: src/tsfile/sequence_reader.cpp.s

.PHONY : src/tsfile/sequence_reader.s

# target to generate assembly for a file
src/tsfile/sequence_reader.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/sequence_reader.cpp.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/sequence_reader.cpp.s
.PHONY : src/tsfile/sequence_reader.cpp.s

src/tsfile/siphash.o: src/tsfile/siphash.cpp.o

.PHONY : src/tsfile/siphash.o

# target to build an object file
src/tsfile/siphash.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/siphash.cpp.o
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/siphash.cpp.o
.PHONY : src/tsfile/siphash.cpp.o

src/tsfile/siphash.i: src/tsfile/siphash.cpp.i

.PHONY : src/tsfile/siphash.i

# target to preprocess a source file
src/tsfile/siphash.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/siphash.cpp.i
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/siphash.cpp.i
.PHONY : src/tsfile/siphash.cpp.i

src/tsfile/siphash.s: src/tsfile/siphash.cpp.s

.PHONY : src/tsfile/siphash.s

# target to generate assembly for a file
src/tsfile/siphash.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/src/tsfile/siphash.cpp.s
	$(MAKE) -f CMakeFiles/tsfile.dir/build.make CMakeFiles/tsfile.dir/src/tsfile/siphash.cpp.s
.PHONY : src/tsfile/siphash.cpp.s

test/io/test_bytebuffer.o: test/io/test_bytebuffer.cpp.o

.PHONY : test/io/test_bytebuffer.o

# target to build an object file
test/io/test_bytebuffer.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/io/test_bytebuffer.cpp.o
.PHONY : test/io/test_bytebuffer.cpp.o

test/io/test_bytebuffer.i: test/io/test_bytebuffer.cpp.i

.PHONY : test/io/test_bytebuffer.i

# target to preprocess a source file
test/io/test_bytebuffer.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/io/test_bytebuffer.cpp.i
.PHONY : test/io/test_bytebuffer.cpp.i

test/io/test_bytebuffer.s: test/io/test_bytebuffer.cpp.s

.PHONY : test/io/test_bytebuffer.s

# target to generate assembly for a file
test/io/test_bytebuffer.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/io/test_bytebuffer.cpp.s
.PHONY : test/io/test_bytebuffer.cpp.s

test/model/test_chunk.o: test/model/test_chunk.cpp.o

.PHONY : test/model/test_chunk.o

# target to build an object file
test/model/test_chunk.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_chunk.cpp.o
.PHONY : test/model/test_chunk.cpp.o

test/model/test_chunk.i: test/model/test_chunk.cpp.i

.PHONY : test/model/test_chunk.i

# target to preprocess a source file
test/model/test_chunk.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_chunk.cpp.i
.PHONY : test/model/test_chunk.cpp.i

test/model/test_chunk.s: test/model/test_chunk.cpp.s

.PHONY : test/model/test_chunk.s

# target to generate assembly for a file
test/model/test_chunk.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/model/test_chunk.cpp.s
.PHONY : test/model/test_chunk.cpp.s

test/test_main.o: test/test_main.cpp.o

.PHONY : test/test_main.o

# target to build an object file
test/test_main.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/test_main.cpp.o
.PHONY : test/test_main.cpp.o

test/test_main.i: test/test_main.cpp.i

.PHONY : test/test_main.i

# target to preprocess a source file
test/test_main.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/test_main.cpp.i
.PHONY : test/test_main.cpp.i

test/test_main.s: test/test_main.cpp.s

.PHONY : test/test_main.s

# target to generate assembly for a file
test/test_main.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/test_main.cpp.s
.PHONY : test/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... clang-format"
	@echo "... unit_test"
	@echo "... tsfile"
	@echo "... src/tsfile/chunk.o"
	@echo "... src/tsfile/chunk.i"
	@echo "... src/tsfile/chunk.s"
	@echo "... src/tsfile/chunk_group.o"
	@echo "... src/tsfile/chunk_group.i"
	@echo "... src/tsfile/chunk_group.s"
	@echo "... src/tsfile/chunk_group_footer.o"
	@echo "... src/tsfile/chunk_group_footer.i"
	@echo "... src/tsfile/chunk_group_footer.s"
	@echo "... src/tsfile/chunk_header.o"
	@echo "... src/tsfile/chunk_header.i"
	@echo "... src/tsfile/chunk_header.s"
	@echo "... src/tsfile/hasher.o"
	@echo "... src/tsfile/hasher.i"
	@echo "... src/tsfile/hasher.s"
	@echo "... src/tsfile/path.o"
	@echo "... src/tsfile/path.i"
	@echo "... src/tsfile/path.s"
	@echo "... src/tsfile/sequence_reader.o"
	@echo "... src/tsfile/sequence_reader.i"
	@echo "... src/tsfile/sequence_reader.s"
	@echo "... src/tsfile/siphash.o"
	@echo "... src/tsfile/siphash.i"
	@echo "... src/tsfile/siphash.s"
	@echo "... test/io/test_bytebuffer.o"
	@echo "... test/io/test_bytebuffer.i"
	@echo "... test/io/test_bytebuffer.s"
	@echo "... test/model/test_chunk.o"
	@echo "... test/model/test_chunk.i"
	@echo "... test/model/test_chunk.s"
	@echo "... test/test_main.o"
	@echo "... test/test_main.i"
	@echo "... test/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

